---
url: "authentication.json"
urls:
  - label: Parking
    value: "smart-parking.json"
  - label: Authentication
    value: "authentication.json"
dom_id: "#swagger-ui"
validatorUrl: "https://online.swagger.io/validator"
oauth2RedirectUrl: "http://localhost:3200/oauth2-redirect.html"
